name: bank-ai-conda
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi=0.116
  - uvicorn=0.35
  - pydantic-settings=2.10
  - numpy=2.3
  - pillow=11.3
  - py-opencv=4.12
  - tesseract=5.5
  - pytesseract=0.3.13
  - pytest=8.4
  - httpx=0.28
  - black=25.1
  - ruff=0.12
  - pip
